[package]
name = "mcp3x6x"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield-struct = "0.12.1"
embedded-hal = "1.0.0"
defmt = { version = "1.0.1", optional = true }

[features]
defmt = ["dep:defmt"]